// Code generated by Kitex v0.5.2. DO NOT EDIT.

package bankservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	api "kitex/kitex_gen/api"
)

func serviceInfo() *kitex.ServiceInfo {
	return bankServiceServiceInfo
}

var bankServiceServiceInfo = NewServiceInfo()

func NewServiceInfo() *kitex.ServiceInfo {
	serviceName := "BankService"
	handlerType := (*api.BankService)(nil)
	methods := map[string]kitex.MethodInfo{
		"GetNameMethod": kitex.NewMethodInfo(getNameMethodHandler, newBankServiceGetNameMethodArgs, newBankServiceGetNameMethodResult, false),
	}
	extra := map[string]interface{}{
		"PackageName": "api",
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.5.2",
		Extra:           extra,
	}
	return svcInfo
}

func getNameMethodHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*api.BankServiceGetNameMethodArgs)
	realResult := result.(*api.BankServiceGetNameMethodResult)
	success, err := handler.(api.BankService).GetNameMethod(ctx, realArg.Request)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newBankServiceGetNameMethodArgs() interface{} {
	return api.NewBankServiceGetNameMethodArgs()
}

func newBankServiceGetNameMethodResult() interface{} {
	return api.NewBankServiceGetNameMethodResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) GetNameMethod(ctx context.Context, request *api.BankNameReq) (r *api.BankNameResp, err error) {
	var _args api.BankServiceGetNameMethodArgs
	_args.Request = request
	var _result api.BankServiceGetNameMethodResult
	if err = p.c.Call(ctx, "GetNameMethod", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
